// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNz07sa3aJySi_vRPmRdOpNvKCAn49d8',
    appId: '1:632689866596:web:c430a1967c03df43966c71',
    messagingSenderId: '632689866596',
    projectId: 'homepal-ug',
    authDomain: 'homepal-ug.firebaseapp.com',
    databaseURL: 'https://homepal-ug-default-rtdb.firebaseio.com',
    storageBucket: 'homepal-ug.appspot.com',
    measurementId: 'G-KF5CHJLTB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3bjlv-1D3KNPDowXyQ2ygjUM-yLajXY',
    appId: '1:632689866596:android:dd3d8f4068caef06966c71',
    messagingSenderId: '632689866596',
    projectId: 'homepal-ug',
    databaseURL: 'https://homepal-ug-default-rtdb.firebaseio.com',
    storageBucket: 'homepal-ug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhalFToUxymdzdOGTsClHwsil3xX2A_WE',
    appId: '1:632689866596:ios:a4afe6e0b4d5eb75966c71',
    messagingSenderId: '632689866596',
    projectId: 'homepal-ug',
    databaseURL: 'https://homepal-ug-default-rtdb.firebaseio.com',
    storageBucket: 'homepal-ug.appspot.com',
    androidClientId: '632689866596-fhnd7i0tesu26n4ekqfcvu46mrr1k2ch.apps.googleusercontent.com',
    iosClientId: '632689866596-p18f2o0pmg9eoe05n3s0eeb36qe5dvu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sunrise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhalFToUxymdzdOGTsClHwsil3xX2A_WE',
    appId: '1:632689866596:ios:107065072251773e966c71',
    messagingSenderId: '632689866596',
    projectId: 'homepal-ug',
    databaseURL: 'https://homepal-ug-default-rtdb.firebaseio.com',
    storageBucket: 'homepal-ug.appspot.com',
    androidClientId: '632689866596-fhnd7i0tesu26n4ekqfcvu46mrr1k2ch.apps.googleusercontent.com',
    iosClientId: '632689866596-29edm3fv91i5d2c57msuhrt3ce7cgif3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sunrise.RunnerTests',
  );
}
